import { z } from 'zod';
import { PAYMENT_METHODS, SIMPLE_PAYMENT_STATUSES } from '../config/constants';
import { money, objectId, optionalText, requiredText } from './common';

/** A manually entered line. Lines for linked rentals are generated by the server. */
const manualLine = z.object({
    description: requiredText(200),
    quantity: z.number().int('Quantity must be a whole number').min(1).max(10_000),
    unitPrice: money,
});

export const createInvoiceBody = z
    .object({
        customerId: objectId,
        productRentalIds: z.array(objectId).max(50).default([]),
        studioRentalIds: z.array(objectId).max(50).default([]),
        items: z.array(manualLine).max(50).default([]),
        tax: money.default(0),
        paymentMethod: z.enum(PAYMENT_METHODS),
        paymentStatus: z.enum(SIMPLE_PAYMENT_STATUSES).default('Pending'),
        notes: optionalText(1000),
    })
    .refine(b => b.productRentalIds.length + b.studioRentalIds.length + b.items.length > 0, {
        message: 'Add at least one line item or link a rental',
        path: ['items'],
    });

export const invoicePaymentBody = z.object({
    paymentStatus: z.enum(SIMPLE_PAYMENT_STATUSES),
});
